[app]
# общие настройки приложения
# STDERR & STDOUT в файл
log2file = no

[db]
# настройки доступа к postgres БД
host = localhost
user = s1api
password = Xie0mahp
name = b

[hypnotoad]
# настройки Hypnotoad. можно использовать любые ключи из конфигурации
# там где нужен массив писать через запятую. если одно значение, то тоже важно ставить запятую в конце
listen = http://127.0.0.1:5000,
workers = 4
proxy = 1
heartbeat_timeout = 30
inactivity_timeout = 30
