# S1 API → Perl (hypnotoad) на 127.0.0.1:5000
location /s1/ {
    auth_basic off;
    proxy_set_header X-Request-Base $scheme://$http_host/s1;
    proxy_pass http://127.0.0.1:5000/api/;
    proxy_set_header Upgrade    $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    client_max_body_size 2m;
    proxy_read_timeout   20s;
}
